const images = [
  {
    url: 'https://assets-a1.kompasiana.com/items/album/2020/12/07/read-5fcda9568ede485d98617872.jpg',
  },
  {
    url: 'https://diskerpus.badungkab.go.id/storage/olds/diskerpus/15-Manfaat-Membaca-Buku-dalam-Kehidupan_838618.jpg',
  },
  {
    url: 'https://cdn1-production-images-kly.akamaized.net/TIpuSykzCa6zqGib7rGGAPMdCjs=/1200x675/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/3154097/original/087220900_1592297644-collage-female-is-reading-book_1421-3697.jpg',
  },
];

const categories = [
  {id: '1', name: 'Pengaturan', icon: 'cog'},
  {id: '2', name: 'Internet', icon: 'wifi'},
  {id: '3', name: 'Battery', icon: 'battery'},
  {id: '4', name: 'Bluetooth', icon: 'bluetooth'},
  {id: '5', name: 'Mobil', icon: 'car'},
  {id: '6', name: 'Awan', icon: 'cloud'},
  {id: '7', name: 'Kopi', icon: 'coffee'},
  {id: '8', name: 'Database', icon: 'database'},
  {id: '9', name: 'Api', icon: 'fire'},
  {id: '10', name: 'Hadiah', icon: 'gift'},
  {id: '11', name: 'Musik', icon: 'music'},
  {id: '12', name: 'Kesehatan', icon: 'heart-pulse'},
  {id: '13', name: 'Kamera', icon: 'camera'},
  {id: '14', name: 'Pesawat', icon: 'airplane'},
  {id: '15', name: 'Buku', icon: 'book'},
  {id: '16', name: 'Uang', icon: 'cash'},
  {id: '17', name: 'Pendidikan', icon: 'school'},
  {id: '18', name: 'Makanan', icon: 'silverware-fork-knife'},
  {id: '19', name: 'Olahraga', icon: 'football'},
  {id: '20', name: 'Film', icon: 'movie'},
  {id: '21', name: 'Game', icon: 'gamepad-variant'},
  {id: '22', name: 'Fashion', icon: 'tshirt-crew'},
  {id: '23', name: 'Kecantikan', icon: 'spa-outline'},
  {id: '24', name: 'Perjalanan', icon: 'briefcase'},
  {id: '25', name: 'Teknologi', icon: 'laptop'},
  {id: '26', name: 'Rumah', icon: 'home'},
  {id: '27', name: 'Kebersihan', icon: 'broom'},
  {id: '28', name: 'Hobi', icon: 'brush'},
  {id: '29', name: 'Elektronik', icon: 'power-plug'},
  {id: '30', name: 'Pertanian', icon: 'tractor'},
];

const topSellingProducts = [
  {
    id: '1',
    imageUrl: require('../assets/images/products/molto.jpg'),
    productName: 'Molto Pewangi Pakaian',
    productPrice: 50000,
    productRating: '4.0',
    totalSold: 100,
  },
  {
    id: '2',
    imageUrl: require('../assets/images/products/cimory.jpg'),
    productName: 'Cimory Fresh Milk',
    productPrice: 38500,
    productRating: '5.0',
    totalSold: 50,
  },
  {
    id: '3',
    imageUrl: require('../assets/images/products/crystaline.jpeg'),
    productName: 'Crystaline Air Mineral',
    productPrice: 24000,
    productRating: '5.0',
    totalSold: 80,
  },
  {
    id: '4',
    imageUrl: require('../assets/images/products/mie.png'),
    productName: 'Indomie Goreng Mie Instan',
    productPrice: 40000,
    productRating: '5.0',
    totalSold: 125,
  },
  {
    id: '5',
    imageUrl: require('../assets/images/products/ciptadent.jpg'),
    productName: 'Pasta Gigi Odol Ciptadent',
    productPrice: 50000,
    productRating: '4.0',
    totalSold: 100,
  },
  {
    id: '6',
    imageUrl: require('../assets/images/products/chitato.jpg'),
    productName: 'Chitato Lite Rasa Rumput Laut',
    productPrice: 38500,
    productRating: '5.0',
    totalSold: 50,
  },
  {
    id: '7',
    imageUrl: require('../assets/images/products/beras.jpg'),
    productName: 'Beras Pulen Wangi Premium 5KG',
    productPrice: 24000,
    productRating: '5.0',
    totalSold: 80,
  },
  {
    id: '8',
    imageUrl: require('../assets/images/products/shampo.jpg'),
    productName: 'Head Shoulders Shampoo Menthol Dingin',
    productPrice: 40000,
    productRating: '5.0',
    totalSold: 125,
  },
  {
    id: '9',
    imageUrl: require('../assets/images/products/molto.jpg'),
    productName: 'Molto Pewangi Pakaian',
    productPrice: 50000,
    productRating: '4.0',
    totalSold: 100,
  },
  {
    id: '10',
    imageUrl: require('../assets/images/products/cimory.jpg'),
    productName: 'Cimory Fresh Milk',
    productPrice: 38500,
    productRating: '5.0',
    totalSold: 50,
  },
];

const newProducts = [
  {
    id: '1',
    imageUrl: require('../assets/images/products/sabun_mandi.jpg'),
    productName: 'Shinzui 500ml - Sabun Mandi Cair',
    productPrice: 50000,
    productRating: '4.0',
    totalSold: 100,
  },
  {
    id: '2',
    imageUrl: require('../assets/images/products/parfume.jpg'),
    productName: 'Gatsby White Up Eeau De Toillete Parfume 50ml',
    productPrice: 38500,
    productRating: '5.0',
    totalSold: 50,
  },
  {
    id: '3',
    imageUrl: require('../assets/images/products/sunlight.jpg'),
    productName: 'Sunlight Jeruk Nipis, Extra Anti Bau, Extra Higienis 650 ml',
    productPrice: 24000,
    productRating: '5.0',
    totalSold: 80,
  },
  {
    id: '4',
    imageUrl: require('../assets/images/products/rinso.jpeg'),
    productName: 'Rinso Molto Detergent Bubuk Deterjen Anti Noda',
    productPrice: 40000,
    productRating: '5.0',
    totalSold: 125,
  },
  {
    id: '5',
    imageUrl: require('../assets/images/products/molto.jpg'),
    productName: 'Molto Pewangi Pakaian',
    productPrice: 50000,
    productRating: '4.0',
    totalSold: 100,
  },
  {
    id: '6',
    imageUrl: require('../assets/images/products/cimory.jpg'),
    productName: 'Cimory Fresh Milk',
    productPrice: 38500,
    productRating: '5.0',
    totalSold: 50,
  },
  {
    id: '7',
    imageUrl: require('../assets/images/products/crystaline.jpeg'),
    productName: 'Crystaline Air Mineral',
    productPrice: 24000,
    productRating: '5.0',
    totalSold: 80,
  },
  {
    id: '8',
    imageUrl: require('../assets/images/products/mie.png'),
    productName: 'Indomie Goreng Mie Instan',
    productPrice: 40000,
    productRating: '5.0',
    totalSold: 125,
  },
  {
    id: '9',
    imageUrl: require('../assets/images/products/molto.jpg'),
    productName: 'Molto Pewangi Pakaian',
    productPrice: 50000,
    productRating: '4.0',
    totalSold: 100,
  },
  {
    id: '10',
    imageUrl: require('../assets/images/products/cimory.jpg'),
    productName: 'Cimory Fresh Milk',
    productPrice: 38500,
    productRating: '5.0',
    totalSold: 50,
  },
];

const recommendation = [
  {
    id: '1',
    imageUrl: require('../assets/images/products/molto.jpg'),
    productName: 'Molto Pewangi Pakaian',
    productPrice: 50000,
    productRating: '4.0',
    totalSold: 100,
  },
  {
    id: '2',
    imageUrl: require('../assets/images/products/cimory.jpg'),
    productName: 'Cimory Fresh Milk',
    productPrice: 38500,
    productRating: '5.0',
    totalSold: 50,
  },
  {
    id: '3',
    imageUrl: require('../assets/images/products/crystaline.jpeg'),
    productName: 'Crystaline Air Mineral',
    productPrice: 24000,
    productRating: '5.0',
    totalSold: 80,
  },
  {
    id: '4',
    imageUrl: require('../assets/images/products/mie.png'),
    productName: 'Indomie Goreng Mie Instan',
    productPrice: 40000,
    productRating: '5.0',
    totalSold: 125,
  },
  {
    id: '5',
    imageUrl: require('../assets/images/products/molto.jpg'),
    productName: 'Molto Pewangi Pakaian',
    productPrice: 50000,
    productRating: '4.0',
    totalSold: 100,
  },
  {
    id: '6',
    imageUrl: require('../assets/images/products/cimory.jpg'),
    productName: 'Cimory Fresh Milk',
    productPrice: 38500,
    productRating: '5.0',
    totalSold: 50,
  },
  {
    id: '7',
    imageUrl: require('../assets/images/products/crystaline.jpeg'),
    productName: 'Crystaline Air Mineral',
    productPrice: 24000,
    productRating: '5.0',
    totalSold: 80,
  },
  {
    id: '8',
    imageUrl: require('../assets/images/products/mie.png'),
    productName: 'Indomie Goreng Mie Instan',
    productPrice: 40000,
    productRating: '5.0',
    totalSold: 125,
  },
  {
    id: '9',
    imageUrl: require('../assets/images/products/molto.jpg'),
    productName: 'Molto Pewangi Pakaian',
    productPrice: 50000,
    productRating: '4.0',
    totalSold: 100,
  },
  {
    id: '10',
    imageUrl: require('../assets/images/products/cimory.jpg'),
    productName: 'Cimory Fresh Milk',
    productPrice: 38500,
    productRating: '5.0',
    totalSold: 50,
  },
  {
    id: '11',
    imageUrl: require('../assets/images/products/ciptadent.jpg'),
    productName: 'Pasta Gigi Odol Ciptadent',
    productPrice: 50000,
    productRating: '4.0',
    totalSold: 100,
  },
  {
    id: '12',
    imageUrl: require('../assets/images/products/chitato.jpg'),
    productName: 'Chitato Lite Rasa Rumput Laut',
    productPrice: 38500,
    productRating: '5.0',
    totalSold: 50,
  },
  {
    id: '13',
    imageUrl: require('../assets/images/products/beras.jpg'),
    productName: 'Beras Pulen Wangi Premium 5KG',
    productPrice: 24000,
    productRating: '5.0',
    totalSold: 80,
  },
  {
    id: '14',
    imageUrl: require('../assets/images/products/shampo.jpg'),
    productName: 'Head Shoulders Shampoo Menthol Dingin',
    productPrice: 40000,
    productRating: '5.0',
    totalSold: 125,
  },
  {
    id: '15',
    imageUrl: require('../assets/images/products/ciptadent.jpg'),
    productName: 'Pasta Gigi Odol Ciptadent',
    productPrice: 50000,
    productRating: '4.0',
    totalSold: 100,
  },
  {
    id: '16',
    imageUrl: require('../assets/images/products/chitato.jpg'),
    productName: 'Chitato Lite Rasa Rumput Laut',
    productPrice: 38500,
    productRating: '5.0',
    totalSold: 50,
  },
  {
    id: '17',
    imageUrl: require('../assets/images/products/beras.jpg'),
    productName: 'Beras Pulen Wangi Premium 5KG',
    productPrice: 24000,
    productRating: '5.0',
    totalSold: 80,
  },
  {
    id: '18',
    imageUrl: require('../assets/images/products/shampo.jpg'),
    productName: 'Head Shoulders Shampoo Menthol Dingin',
    productPrice: 40000,
    productRating: '5.0',
    totalSold: 125,
  },
  {
    id: '19',
    imageUrl: require('../assets/images/products/ciptadent.jpg'),
    productName: 'Pasta Gigi Odol Ciptadent',
    productPrice: 50000,
    productRating: '4.0',
    totalSold: 100,
  },
  {
    id: '20',
    imageUrl: require('../assets/images/products/chitato.jpg'),
    productName: 'Chitato Lite Rasa Rumput Laut',
    productPrice: 38500,
    productRating: '5.0',
    totalSold: 50,
  },
  {
    id: '21',
    imageUrl: require('../assets/images/products/sabun_mandi.jpg'),
    productName: 'Shinzui 500ml - Sabun Mandi Cair',
    productPrice: 50000,
    productRating: '4.0',
    totalSold: 100,
  },
  {
    id: '22',
    imageUrl: require('../assets/images/products/parfume.jpg'),
    productName: 'Gatsby White Up Eeau De Toillete Parfume 50ml',
    productPrice: 38500,
    productRating: '5.0',
    totalSold: 50,
  },
  {
    id: '23',
    imageUrl: require('../assets/images/products/sunlight.jpg'),
    productName: 'Sunlight Jeruk Nipis, Extra Anti Bau, Extra Higienis 650 ml',
    productPrice: 24000,
    productRating: '5.0',
    totalSold: 80,
  },
  {
    id: '24',
    imageUrl: require('../assets/images/products/rinso.jpeg'),
    productName: 'Rinso Molto Detergent Bubuk Deterjen Anti Noda',
    productPrice: 40000,
    productRating: '5.0',
    totalSold: 125,
  },
  {
    id: '25',
    imageUrl: require('../assets/images/products/sabun_mandi.jpg'),
    productName: 'Shinzui 500ml - Sabun Mandi Cair',
    productPrice: 50000,
    productRating: '4.0',
    totalSold: 100,
  },
  {
    id: '26',
    imageUrl: require('../assets/images/products/parfume.jpg'),
    productName: 'Gatsby White Up Eeau De Toillete Parfume 50ml',
    productPrice: 38500,
    productRating: '5.0',
    totalSold: 50,
  },
  {
    id: '27',
    imageUrl: require('../assets/images/products/sunlight.jpg'),
    productName: 'Sunlight Jeruk Nipis, Extra Anti Bau, Extra Higienis 650 ml',
    productPrice: 24000,
    productRating: '5.0',
    totalSold: 80,
  },
  {
    id: '28',
    imageUrl: require('../assets/images/products/rinso.jpeg'),
    productName: 'Rinso Molto Detergent Bubuk Deterjen Anti Noda',
    productPrice: 40000,
    productRating: '5.0',
    totalSold: 125,
  },
  {
    id: '29',
    imageUrl: require('../assets/images/products/sabun_mandi.jpg'),
    productName: 'Shinzui 500ml - Sabun Mandi Cair',
    productPrice: 50000,
    productRating: '4.0',
    totalSold: 100,
  },
  {
    id: '30',
    imageUrl: require('../assets/images/products/parfume.jpg'),
    productName: 'Gatsby White Up Eeau De Toillete Parfume 50ml',
    productPrice: 38500,
    productRating: '5.0',
    totalSold: 50,
  },
];

export {images, categories, topSellingProducts, newProducts, recommendation};
